# Generated by Django 5.2.7 on 2025-10-07 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ingeniero', 'Ingeniero(a)'), ('arquitecto', 'Arquitecto(a)'), ('senior', 'Señor(a)')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='templates_docs/')),
                ('services_tag', models.CharField(max_length=100)),
                ('formats_tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('is_detection', models.BooleanField(default=False)),
                ('is_protection', models.BooleanField(default=False)),
                ('is_human_safety', models.BooleanField(default=False)),
                ('deliver_autocad', models.BooleanField(default=False)),
                ('deliver_revit', models.BooleanField(default=False)),
                ('building_type', models.CharField(blank=True, choices=[('residential', 'Residencial'), ('commercial', 'Comercial')], max_length=20)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('manual_requirements', models.TextField(blank=True)),
                ('manual_items_sh', models.TextField(blank=True)),
                ('manual_items_detection', models.TextField(blank=True)),
                ('manual_items_protection', models.TextField(blank=True)),
                ('payment_advance', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('payment_first_version', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('payment_final', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('delivery_time_value', models.IntegerField(blank=True, null=True)),
                ('delivery_time_unit', models.CharField(blank=True, choices=[('days', 'Días'), ('weeks', 'Semanas'), ('months', 'Meses')], max_length=10)),
                ('generated_doc', models.FileField(blank=True, null=True, upload_to='generated_quotes/')),
                ('value_protection', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value_detection', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('value_human_safety', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.client')),
                ('norms', models.ManyToManyField(blank=True, to='quotes.norm')),
                ('template_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotes.templatedoc')),
            ],
        ),
    ]
