# Generated by Django 5.2.7 on 2025-10-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='norm',
            name='service_type',
            field=models.CharField(choices=[('detection', 'Detección de incendios'), ('protection', 'Protección contra incendios'), ('human_safety', 'Seguridad humana')], default='protection', max_length=20),
            preserve_default=False,
        ),
    ]
