# Generated by Django 5.2.7 on 2025-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_norm_service_type_norm_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norm',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
