# Generated by Django 5.2.7 on 2025-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_alter_norm_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, choices=[('ingeniero', 'Ingeniero(a)'), ('arquitecto', 'Arquitecto(a)'), ('senior', 'Señor(a)')], max_length=20),
        ),
    ]
