# Generated by Django 5.2.7 on 2025-10-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_client_full_name_alter_client_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='service_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
