# Generated by Django 5.2.7 on 2025-10-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quote_service_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norm',
            old_name='default_selected',
            new_name='is_default',
        ),
    ]
