# Generated by Django 5.2.7 on 2026-05-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_rename_default_selected_norm_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, choices=[('senor', 'Señor'), ('senora', 'Señora'), ('ingeniero', 'Ingeniero'), ('ingeniera', 'Ingeniera'), ('arquitecto', 'Arquitecto'), ('arquitecta', 'Arquitecta')], max_length=20),
        ),
    ]
