# Generated by Django 5.2.7 on 2026-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_client_email_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='norm',
            old_name='is_default',
            new_name='default_detection',
        ),
        migrations.AddField(
            model_name='norm',
            name='default_human_safety',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='norm',
            name='default_protection',
            field=models.BooleanField(default=False),
        ),
    ]
