# Generated by Django 5.2.7 on 2026-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_rename_is_default_norm_default_detection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='norm',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
