# Generated by Django 5.2.7 on 2026-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_norm_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('next_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
