# Generated by Django 5.2.7 on 2026-07-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quotecounter_quote_quote_number_quote_quote_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_value_revit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='value_detection_revit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='value_human_safety_revit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='value_protection_revit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
