# Generated by Django 5.2.7 on 2026-07-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_quote_grand_total_quote_total_value_revit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='additional_notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
