# Generated by Django 5.2.7 on 2025-10-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_norm_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norm',
            name='service_type',
        ),
        migrations.AddField(
            model_name='norm',
            name='services',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='norm',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
